{"pageProps":{"html":"<!doctype html>\n<html lang=\"ja\">\n<head>\n<meta charset=\"utf-8\">\n<title>orange/note: ArchLinuxのPythonでpkg_resourcesモジュールが見つからない</title>\n<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\n<meta name=\"author\" content=\"http://www.hatena.ne.jp/lufiabb/\">\n</head>\n<body>\n<nav>\n\t<h1>メニュー</h1>\n\t<ul>\n\t<li><a href=\"/notes/index.html\">orange/note</a></li>\n\t<li><a href=\"/notes/pc.html\">PC関連</a></li>\n\t<li><a href=\"/notes/web.html\">web製作</a></li>\n\t<li><a href=\"/notes/sec.html\">セキュリティ</a></li>\n\t<li><a href=\"/notes/hobby.html\">本・ゲーム</a></li>\n\t<li><a href=\"/notes/junk.html\">ジャンク</a></li>\n\t</ul>\n</nav>\n<main>\n\t<p class=\"revision\">2022年2月9日作成</p>\n\t<section>\n\t\t<h1>ArchLinuxのPythonでpkg_resourcesモジュールが見つからない</h1>\n\t\t<p>ArchLinuxで<em>awslogs</em>を実行したとき以下のエラーが発生した。</p>\n\t\t<pre><code class=\"console\">$ awslogs\nTraceback (most recent call last):\n  File &quot;/usr/bin/awslogs&quot;, line 33, in &lt;module&gt;\n    sys.exit(load_entry_point('awslogs==0.14.0', 'console_scripts', 'awslogs')())\n  File &quot;/usr/bin/awslogs&quot;, line 25, in importlib_load_entry_point\n    return next(matches).load()\n  File &quot;/usr/lib/python3.10/importlib/metadata/__init__.py&quot;, line 162, in load\n    module = import_module(match.group('module'))\n  File &quot;/usr/lib/python3.10/importlib/__init__.py&quot;, line 126, in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1050, in _gcd_import\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1027, in _find_and_load\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 992, in _find_and_load_unlocked\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 241, in _call_with_frames_removed\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1050, in _gcd_import\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1027, in _find_and_load\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1006, in _find_and_load_unlocked\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 688, in _load_unlocked\n  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 883, in exec_module\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 241, in _call_with_frames_removed\n  File &quot;/usr/lib/python3.10/site-packages/awslogs/__init__.py&quot;, line 1, in &lt;module&gt;\n    from ._version import __version__  # noqa\n  File &quot;/usr/lib/python3.10/site-packages/awslogs/_version.py&quot;, line 1, in &lt;module&gt;\n    from pkg_resources import get_distribution\nModuleNotFoundError: No module named 'pkg_resources'</code></pre>\n\t\t<p>どうやら<em>pkg_resources</em>は<strong>python-setuptools</strong>に含まれているようだけど、\n\t\tこれは<strong>awslogs</strong>パッケージの<em>makedepends</em>とされているので、\n\t\tパッケージの掃除をしたときに消してしまったらしい。</p>\n\t\t<p>なので解消するには、<strong>python-setuptools</strong>パッケージをインストールすればよい。</p>\n\t\t<pre><code class=\"console\">$ sudo pacman -S --asdeps python-setuptools</code></pre>\n\t</section>\n</main>\n<aside>\n\t<h1>やっていること</h1>\n\t<ul>\n\t<li><a href=\"/plan9/index.html\">Plan 9</a></li>\n\t<li><a href=\"http://web.me.com/lufia/alefcompiler/alef/\">Alefコンパイラを読む</a></li>\n\t</ul>\n</aside>\n<footer>\n\t<p>見れない、表示がおかしい場合は、動作環境を添えて<a href=\"mailto:webmaster@lufia.org\">webmaster@lufia.org</a>まで連絡ください。</p>\n</footer>\n</body>\n</html>\n"},"__N_SSG":true}